#!/usr/bin/php
<?php

require dirname(__FILE__).'/vendor/autoload.php';
require dirname(__FILE__).'/src/Req.php';

// Create a commando command.
$cmd = new Commando\Command();

//Add the filename argument
$cmd->option()
    ->referToAs('Filename: ')
    ->describedAs("The request JSON file");

// Get a colors instance.
$c = new \Colors\Color();

// Declare the response variable, save it for later.
$response;

if (empty($cmd[0])) {
    echo $c("Please provide a JSON file or valid URL as the first argument")->red().PHP_EOL;
}
else
{
    if (filter_var($cmd[0], FILTER_VALIDATE_URL)) {
        // GET the URL.
        $response = Req::forge($cmd[0])->get();
    }
    else {
        // Check it's a file.
        if (!is_file($cmd[0]))
        {
            print $c("Invalid argument 0:")->white()->highlight('red').PHP_EOL;
            print $c("  Using a request JSON file? Check that the filepath exists.")->yellow().PHP_EOL;
            print $c("  Using a URL? Check that you've included the http:// or https:// prefix.")->yellow().PHP_EOL;
        }
        else
        {
            // get contents, execute a request based on them.
        }
    }
}

echo $response.PHP_EOL;



